### ISSUE TITLE
MediaType not set on path /auth/realms/master/avatar-provider

### ISSUE THREAD

**Issue by ghost** [thomasdarimont/keycloak-avatar-minio-extension#6]
I started this up according to the instructions: running minio with docker and running a local standalone copy of keycloak 13.0.1 under Java8. I can see the theme and pick it but when I try to upload an image via account theme I get an error complaining about lack of MediaType.
```
07:22:37,064 ERROR [org.keycloak.headers.DefaultSecurityHeadersProvider] (default task-4) MediaType not set on path /auth/realms/master/avatar-provider/, with response status 500
07:22:37,065 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-4) Uncaught server error: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.keycloak.keycloak-services@12.0.4//org.keycloak.headers.DefaultSecurityHeadersProvider.addHeaders(DefaultSecurityHeadersProvider.java:75)
	at org.keycloak.keycloak-services@12.0.4//org.keycloak.services.filters.KeycloakSecurityHeadersFilter.filter(KeycloakSecurityHeadersFilter.java:39)
	at org.jboss.resteasy.resteasy-jaxrs@3.13.2.Final//org.jboss.resteasy.core.interception.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:357)
```
It's the same error reported in https://github.com/thomasdarimont/keycloak-avatar-minio-extension/issues/5
but there are other questions in that ticket and I wanted to highlight this one.

**Comment by ghost** [comment]
This is the request that fails (from wireshark)

```
Hypertext Transfer Protocol
     [truncated]POST /auth/realms/master/avatar-provider/?account&referrer=security-admin-console&referrer_uri=http%3A%2F%2F127.0.0.1%3A8180%2Fauth%2Fadmin%2Fmaster%2Fconsole%2F%23%2Frealms%2Fmaster%2Fusers%2Fc9a9cdee-7ee7-479a-a00b-2789b989a
    Host: 127.0.0.1:8180\r\n
    Connection: keep-alive\r\n
    Content-Length: 226913\r\n
    Cache-Control: max-age=0\r\n
    sec-ch-ua: "Chromium";v="94", "Google Chrome";v="94", ";Not A Brand";v="99"\r\n
    sec-ch-ua-mobile: ?0\r\n
    sec-ch-ua-platform: "Linux"\r\n
    Upgrade-Insecure-Requests: 1\r\n
    Origin: null\r\n
    Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryv8y4QuNseN9Jj8LQ\r\n
    User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36\r\n
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9\r\n
    Sec-Fetch-Site: same-origin\r\n
    Sec-Fetch-Mode: navigate\r\n
    Sec-Fetch-User: ?1\r\n
    Sec-Fetch-Dest: document\r\n
    Accept-Encoding: gzip, deflate, br\r\n
    Accept-Language: en-GB,en-US;q=0.9,en;q=0.8\r\n
     [truncated]Cookie: AUTH_SESSION_ID=24fed4e7-335e-4005-a8b4-1a5e4a0f08d5.benedict; AUTH_SESSION_ID_LEGACY=24fed4e7-335e-4005-a8b4-1a5e4a0f08d5.benedict; KEYCLOAK_LOCALE=en; KEYCLOAK_SESSION=master/c9a9cdee-7ee7-479a-a00b-2789b989a1aa/24fe
    \r\n
    [Full request URI [truncated]: http://127.0.0.1:8180/auth/realms/master/avatar-provider/?account&referrer=security-admin-console&referrer_uri=http%3A%2F%2F127.0.0.1%3A8180%2Fauth%2Fadmin%2Fmaster%2Fconsole%2F%23%2Frealms%2Fmaster%2Fusers%2]
    [HTTP request 1/1]
    [Response in frame: 44322]
    File Data: 226913 bytes
MIME Multipart Media Encapsulation, Type: multipart/form-data, Boundary: "----WebKitFormBoundaryv8y4QuNseN9Jj8LQ"
    [Type: multipart/form-data]
    First boundary: ------WebKitFormBoundaryv8y4QuNseN9Jj8LQ\r\n
    Encapsulated multipart part:  (image/png)
        Content-Disposition: form-data; name="image"; filename="astrolab-512x512.png"\r\n
        Content-Type: image/png\r\n\r\n
        Portable Network Graphics
            PNG Signature: 89504e470d0a1a0a
            Image Header (IHDR)
            Physical pixel dimensions (pHYs)
            Image last-modification time (tIME)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image data chunk (IDAT)
            Image Trailer (IEND)
    Boundary: \r\n------WebKitFormBoundaryv8y4QuNseN9Jj8LQ\r\n
    Encapsulated multipart part: 
        Content-Disposition: form-data; name="stateChecker"\r\n\r\n
        Data (43 bytes)
    Boundary: \r\n------WebKitFormBoundaryv8y4QuNseN9Jj8LQ\r\n
    Encapsulated multipart part: 
        Content-Disposition: form-data; name="submitAction"\r\n\r\n
        Data (4 bytes)
    Last boundary: \r\n------WebKitFormBoundaryv8y4QuNseN9Jj8LQ--\r\n
```
I looked at the source code that is supposed to accept this request. That's at `com.github.thomasdarimont.keycloak.avatar.AvatarResource.uploadCurrentUserAvatarImage(MultipartFormDataInput, UriInfo)`
and it is annotated with `@Consumes(MediaType.MULTIPART_FORM_DATA)` and that matches the request being sent. So it looks like it ought to work but it doesn't.

**Comment by sycale-duallab** [comment]
Any updates?

**Comment by ghost** [comment]
No. Because of this problem I did not use this extension.

**Comment by michaelottofits** [comment]
https://github.com/thomasdarimont/keycloak-avatar-minio-extension/blob/master/avatar-minio-extension-module/src/main/java/com/github/thomasdarimont/keycloak/avatar/AvatarResourceProviderFactory.java#L16-L18
remove the if statement. The factory is called only once. The method of the resource cannot be called then because only the first keycloak session is valid but invalid for other realms.

**Comment by Burzumm** [comment]
I have exactly the same error, did anyone manage to solve the problem?
I use jboss/keycloak:16.1.1 in container. Delete the if statement did not help.

**Comment by der-imp** [comment]
If this topic is still an issue. Since a Keycloak reelase you have to specify each MediaType for responses there the MafiaType could not be extracted. 
I Change the line 
https://github.com/thomasdarimont/keycloak-avatar-minio-extension/blob/594b91c5013920dc9022e53ebb405c75ce7bd6f2/avatar-minio-extension-module/src/main/java/com/github/thomasdarimont/keycloak/avatar/AvatarResource.java#L101

into 
`return Response.ok().type(MediaType.APPLICATION_JSON).build()`

or whatever MediaType you prefere there.
